### ISSUE TITLE
opencv?

### ISSUE THREAD

**Issue by InonS** [tyiannak/paura#2]
Hi @tyiannak!

I the README.md, you require installation of OpenCV, but I couldn't find any calls to it in the repo.

Could you please explain why this is a dependency?

**Comment by tyiannak** [comment]
Thank for the comment. Opencv (cv2) is used only for realtime plotting functionality (i.e. to plot the signal features in an online basis), since it is much faster than other methods such as matplotlib (there are several calls per second and matplotlib would be much slower)

**Comment by InonS** [comment]
I wasn't aware of cv2, or OpenCV's plotting functionality. Thanks!
